# -------------------------------------------------- #
#                 General Settings                   #
# -------------------------------------------------- #
# Available languages: en, tr
language: en

prefix: "&6AvSword &8Â»"

# -------------------------------------------------- #
#                 Sword Settings                     #
# -------------------------------------------------- #
swords:
  Enderman:
    enabled: true
    target-enemy-only: false
    cooldown: 90
    custom-model-data: 101
    effect: ENDERMAN
    teleport-distance: 10
    radius: 0
    effect-level: 0
    effect-duration: 0
    sound:
      name: "ENTITY_ENDERMAN_TELEPORT"
      volume: 1.0
      pitch: 1.0

  Dragon:
    enabled: true
    target-enemy-only: true
    cooldown: 90
    custom-model-data: 102
    effect: DRAGON
    breath-duration: 5
    radius: 0
    effect-level: 0
    effect-duration: 0
    sound:
      name: "ENTITY_ENDER_DRAGON_GROWL"
      volume: 1.2
      pitch: 0.9

  Spider:
    enabled: true
    target-enemy-only: true
    cooldown: 90
    custom-model-data: 103
    effect: SPIDER
    radius: 10
    effect-level: 0
    effect-duration: 5
    sound:
      name: "ENTITY_SPIDER_AMBIENT"
      volume: 1.0
      pitch: 1.3

  Shulker:
    enabled: true
    target-enemy-only: true
    cooldown: 90
    custom-model-data: 104
    effect: LEVITATION
    radius: 5
    effect-level: 1
    effect-duration: 2
    sound:
      name: "ENTITY_SHULKER_SHOOT"
      volume: 1.0
      pitch: 1.0

  Phantom:
    enabled: true
    target-enemy-only: true
    cooldown: 90
    custom-model-data: 105
    effect: PHANTOM
    radius: 5
    effect-level: 0
    effect-duration: 5
    sound:
      name: "ENTITY_PHANTOM_SWOOP"
      volume: 1.0
      pitch: 1.0

# Plugin has built-in support for WorldGuard safe zones.
# Safe zones - Format: "x1,y1,z1 x2,y2,z2 world_name"
safe-zones:
  example_zone: "0,0,0 100,100,100 world"
  spawn: "-50,60,-50 50,80,50 world"